name:                Knights-And-Rage
version:             0.0.8.0
github:              "daniehhu/project-knights-and-rage"
license:             BSD3
author:              "Daniel Hao Huynh"
maintainer:          "daniehhu@stud.ntnu.no"
copyright:           "2022 Daniel Hao Huynh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Please see the README on GitHub at <https://git.gvk.idi.ntnu.no/course/prog2006/as/daniehhu/project-knights-and-rage>

dependencies:
- base >= 4.7 && < 5
- split
- random 
- time
- haskeline

library:
  source-dirs: 
    - src
  
executables:
  Knights-And-Rage-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Knights-And-Rage

tests:
  Knights-And-Rage-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Knights-And-Rage
    - HUnit